<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6hTPCk0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6hTPCk0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6hTPCk0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6hTPCk0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6hTPCk0\App_KernelDevDebugContainer([
    'container.build_hash' => '6hTPCk0',
    'container.build_id' => '6ceed87f',
    'container.build_time' => 1712210633,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6hTPCk0');
